#!/usr/bin/env python3
"""
Build channel monthly metrics from Bark_Trading_Diagnostic.xlsx (Data sheet).
Output: tables (YearMonth, Sessions, Submissions, Sub Rate, Revenue, Spend, Profit, ROAS)
and chart-ready JS arrays for ch2VolumeConversionData, ch1Monthly, ch2Monthly, ch3Monthly.
"""
import pandas as pd
from pathlib import Path

EXCEL_PATH = Path(__file__).resolve().parent / "Bark_Trading_Diagnostic.xlsx"
OUTPUT_JS_PATH = Path(__file__).resolve().parent / "channel_monthly_chart_data.js"

# Column names in Data sheet
COL_SESSIONS = "Project Session Count, start"
COL_SUBMISSIONS = "Project Count, submitted"
COL_REVENUE = "PPR Revenue £"
COL_SPEND = "Marketing Spend £"
COL_PROFIT = "APR (Profit) £ "
COUNTRY_COL = "Country (view)"
CHANNEL_COL = "Channel"
YEARMONTH_COL = "YearMonth"

# UK filter
UK_VALUE = "United Kingdom"

# YearMonths we want (Jul 2024 -> Dec 2025)
WANTED_MONTHS = [
    "2024-07", "2024-08", "2024-09", "2024-10", "2024-11", "2024-12",
    "2025-01", "2025-02", "2025-03", "2025-04", "2025-05", "2025-06",
    "2025-07", "2025-08", "2025-09", "2025-10", "2025-11", "2025-12",
]

MONTH_LABELS = {
    "2024-07": "Jul'24", "2024-08": "Aug'24", "2024-09": "Sep'24", "2024-10": "Oct'24",
    "2024-11": "Nov'24", "2024-12": "Dec'24", "2025-01": "Jan'25", "2025-02": "Feb'25",
    "2025-03": "Mar'25", "2025-04": "Apr'25", "2025-05": "May'25", "2025-06": "Jun'25",
    "2025-07": "Jul'25", "2025-08": "Aug'25", "2025-09": "Sep'25", "2025-10": "Oct'25",
    "2025-11": "Nov'25", "2025-12": "Dec'25",
}


def load_and_aggregate():
    df = pd.read_excel(EXCEL_PATH, sheet_name="Data")
    df = df[df[COUNTRY_COL] == UK_VALUE]
    df = df[df[YEARMONTH_COL].isin(WANTED_MONTHS)]

    agg = df.groupby([CHANNEL_COL, YEARMONTH_COL], as_index=False).agg({
        COL_SESSIONS: "sum",
        COL_SUBMISSIONS: "sum",
        COL_REVENUE: "sum",
        COL_SPEND: "sum",
        COL_PROFIT: "sum",
    })
    agg["Sub Rate"] = (agg[COL_SUBMISSIONS] / agg[COL_SESSIONS].replace(0, float("nan")) * 100).round(1)
    agg["ROAS"] = (agg[COL_REVENUE] / agg[COL_SPEND].replace(0, float("nan"))).round(2)
    return agg


def table_for_channel(agg, channel):
    sub = agg[agg[CHANNEL_COL] == channel].copy()
    sub = sub.sort_values(YEARMONTH_COL)
    sub = sub.rename(columns={
        COL_SESSIONS: "Sessions",
        COL_SUBMISSIONS: "Submissions",
        COL_REVENUE: "Revenue",
        COL_SPEND: "Spend",
        COL_PROFIT: "Profit",
    })
    sub["Sub Rate"] = sub["Sub Rate"].fillna(0).astype(float)
    return sub[[YEARMONTH_COL, "Sessions", "Submissions", "Sub Rate", "Revenue", "Spend", "Profit", "ROAS"]]


def chart_row(ym, sessions, sub_rate):
    """One chart point: month label, sessions in thousands (for chart scale), subRate as number."""
    return {
        "month": MONTH_LABELS.get(ym, ym),
        "sessions": round(sessions / 1000, 1),
        "subRate": round(float(sub_rate), 1),
    }


def channel_to_chart_array(sub):
    return [chart_row(row[YEARMONTH_COL], row["Sessions"], row["Sub Rate"]) for _, row in sub.iterrows()]


def format_table_print(df):
    df = df.copy()
    df["Sessions"] = df["Sessions"].apply(lambda x: f"{int(x):,}")
    df["Submissions"] = df["Submissions"].apply(lambda x: f"{int(x):,}")
    df["Sub Rate"] = df["Sub Rate"].apply(lambda x: f"{x:.1f}%" if pd.notna(x) else "")
    df["Revenue"] = df["Revenue"].apply(lambda x: f"£{int(x):,}" if pd.notna(x) else "")
    df["Spend"] = df["Spend"].apply(lambda x: f"£{int(x):,}" if pd.notna(x) else "")
    df["Profit"] = df["Profit"].apply(lambda x: f"£{int(x):,}" if pd.notna(x) else "")
    df["ROAS"] = df["ROAS"].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "")
    return df


def main():
    agg = load_and_aggregate()

    channels = ["Channel 1", "Channel 2", "Channel 3"]
    tables = {}
    chart_arrays = {}

    for ch in channels:
        t = table_for_channel(agg, ch)
        tables[ch] = t
        # For chart: use same column names as in table_for_channel output
        t_chart = t.rename(columns={YEARMONTH_COL: YEARMONTH_COL})
        chart_arrays[ch] = channel_to_chart_array(t_chart)

    # Print tables (user format)
    for ch in channels:
        print(f"\n{ch} Monthly (UK) — SUMIFS")
        print("-" * 80)
        print(format_table_print(tables[ch]).to_string(index=False))

    # Write JS file for pasting into HTML
    with open(OUTPUT_JS_PATH, "w") as f:
        f.write("// Generated by build_channel_monthly.py — paste into Bark_Trading_Diagnostic.html\n\n")
        f.write("// Channel 2 (UK): Volume vs conversion — full monthly Jul'24–Dec'25\n")
        f.write("const ch2VolumeConversionData = ")
        f.write(repr(chart_arrays["Channel 2"]))
        f.write(";\n\n")
        f.write("// UK Channels side-by-side: Sessions + Sub Rate by channel\n")
        f.write("const ch1Monthly = ")
        f.write(repr(chart_arrays["Channel 1"]))
        f.write(";\nconst ch2Monthly = ")
        f.write(repr(chart_arrays["Channel 2"]))
        f.write(";\nconst ch3Monthly = ")
        f.write(repr(chart_arrays["Channel 3"]))
        f.write(";\n")

    print(f"\nChart data written to {OUTPUT_JS_PATH}")


if __name__ == "__main__":
    main()
